services:
  cache:
    image: memcached:alpine
    ports:
      - "11211:11211"
    restart: always
    environment:
      MEMCACHIER_SERVERS: cache
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    env_file:
      - .env
    build: .
    ports:
      - "5000:5000"
    depends_on:
      cache:
        condition: service_healthy
    restart: always
